eTickets/eTickets/Controllers/ActorController.cs
using eTickets.Data;
using eTickets.Data.Services;
//using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class ActorController : Controller
    {
        //private readonly AppDbContext _context;
        private readonly IActorService _service;

        public ActorController(IActorService service)
        {
            _service = service;  
        }
        public async Task<IActionResult> Index()
        {
            // var data = await _context.GetAllAsync();
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Actor/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        //Get: Actor/details/1
        public async Task<IActionResult> Details(int id)
        {
            // var actorDetails = await _context.GetByIdAsync(id);
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }

        //Get: Actors/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }

        //Get: Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null)
            {
                return View("NotFound");
            }
            return View(actorDetails);
        }

        //if you want to still use the same name make
        //[HttpPost, ActionName("Delete")]

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/eTickets/Controllers/CinemaController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class CinemaController : Controller
    {
        // private readonly AppDbContext _context;
        private readonly ICinemaService _service;

        public CinemaController(ICinemaService service)
        {
            _service = service;
        }
        //public CinemaController(AppDbContext context)
        //{
        //    _context = context;  
        //}
        public async Task<IActionResult> Index()
        {
            var allCinemas = await _service.GetAllAsync();
            return View(allCinemas);
        }
        //Get: Cinema/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        //Get: Cinema/details/1
        public async Task<IActionResult> Details(int id)
        {
            // var cinemaDetails = await _context.GetByIdAsync(id);
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null)
            {
                return View("NotFound");
            }
            return View(cinemaDetails);
        }

        //Get: Cinema/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null)
            {
                return View("NotFound");
            }
            return View(cinemaDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            await _service.UpdateAsync(id, cinema);
            return RedirectToAction(nameof(Index));
        }

        //Get: Cinema/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null)
            {
                return View("NotFound");
            }
            return View(cinemaDetails);
        }

        //if you want to still use the same name make
        //[HttpPost, ActionName("Delete")]

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/eTickets/Controllers/MovieController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class MovieController : Controller
    {
       // private readonly AppDbContext _context;

        private readonly IMovieService _service;

        //public MovieController(AppDbContext context)
        //{
        //    _context = context;  
        //}
        public MovieController(IMovieService service)
        {
            _service = service;
        }


        public async Task<IActionResult> Index()
        {
            // var allMovies = await _context.Movie.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();
            var allMovies = await _service.GetAllAsync(n => n.Cinema);
            return View(allMovies);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);

            if (!string.IsNullOrEmpty(searchString))
            {
               // var ser = searchString.ToUpper();
                var filteredResult = allMovies.Where(n => n.Name.Contains(searchString) || 
                  n.Description.Contains(searchString)).ToList();
                return View("Index",filteredResult);
            }
            return View("Index",allMovies);
        }

        //Get: Movie/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            return View(movieDetails);
        }

        //Get: Movie/Create
        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinema = new SelectList(movieDropdownsData.Cinema, "Id", "Name");
            ViewBag.Producer = new SelectList(movieDropdownsData.Producer, "Id", "FullName");
            ViewBag.Actor = new SelectList(movieDropdownsData.Actor, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();
                ViewBag.Cinema = new SelectList(movieDropdownsData.Cinema, "Id", "Name");
                ViewBag.Producer = new SelectList(movieDropdownsData.Producer, "Id", "FullName");
                ViewBag.Actor = new SelectList(movieDropdownsData.Actor, "Id", "FullName");

                return View(movie);
            }
            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        //Get: Movie/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if(movieDetails == null) { return View("Not Found"); }

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actor_Movie.Select(n => n.ActorId).ToList(),
            };

            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinema = new SelectList(movieDropdownsData.Cinema, "Id", "Name");
            ViewBag.Producer = new SelectList(movieDropdownsData.Producer, "Id", "FullName");
            ViewBag.Actor = new SelectList(movieDropdownsData.Actor, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,NewMovieVM movie)
        {
            if (id != movie.Id) return View("Not Found");
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();
                ViewBag.Cinema = new SelectList(movieDropdownsData.Cinema, "Id", "Name");
                ViewBag.Producer = new SelectList(movieDropdownsData.Producer, "Id", "FullName");
                ViewBag.Actor = new SelectList(movieDropdownsData.Actor, "Id", "FullName");

                return View(movie);
            }
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/eTickets/Controllers/OrderController.cs
using eTickets.Data.Cart;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class OrderController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;
        public OrderController(IMovieService movieService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _orderService = orderService;
            _movieService = movieService;
            _shoppingCart = shoppingCart;
        }   
        public async Task<IActionResult> Index()
        {
            string rn = (string)TempData["Role"];
            int userId = (int)HttpContext.Session.GetInt32("id");
           
            if (rn == "3" || rn == null)
            {
                var orders = await _orderService.GetOrdersByAdminIdAsync(userId);
                return View(orders);
            }
            else
            {
                var orders = await _orderService.GetOrdersByUserIdAsync(userId);
                return View(orders);
            }
        }

        public IActionResult ShoppingCart()
        {
            //Returns list of Shopping Cart Items
            var items = _shoppingCart.GetShoppingCartItem();
            _shoppingCart.ShoppingCartItem = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCardTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _movieService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _movieService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItem();
            int userId = (int)HttpContext.Session.GetInt32("id");
            string userEmailAddress = HttpContext.Session.GetString("Email");
            await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }

        public async Task<IActionResult> Order(int id,string status)
        {
            await _orderService.OrderAsync(id, status);
            return RedirectToAction("Index");
        }
    }
}

eTickets/eTickets/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
         <h1 class="text-info">Something is Wrong!!!</h1>
         <hr/>
         <a class="btn btn-outline-success" asp-controller="Movie" asp-action="Index">Home Page</a>
    </div>
</div>

eTickets/eTickets/Views/Shared/_CreateItem.cshtml
@using Microsoft.AspNetCore.Http
@model string

 @if (Context.Session.GetString("Rid") == "3"){
        <div style="position:fixed;right:25px;bottom:25px" class="text-white">
            <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i>&nbsp;Add New</a>
        </div>
    }

eTickets/eTickets/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movie" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                         @if (Context.Session.GetString("Rid") == "3")
                        {
                             <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                              </a>
                             <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i>&nbsp;Cinemas</a>
                                <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i>&nbsp;Producers</a>
                                <a class="dropdown-item" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i>&nbsp;Actors</a>
                            </div>
                             </li>
                        }
                         <li class="navbar-nav flex-grow-1">
                               <a class="nav-link text-dark" asp-controller="Movie" asp-action="Index"><i class="badge-info bi-film"></i>&nbsp;Movies</a>
                         </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Movie" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                     @if (Context.Session.GetString("id") != null)
                     {
                     @* User Profile section*@
                     <div class="dropdown">
                        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                                aria-expanded="false">
                            <i class="bi bi-person-badge"></i> Hello @Context.Session.GetString("name")
                            </button>
                        <ul class="dropdown-menu" aria-labelledby="profile-btn">
                            <li>
                                <a class="dropdown-item" asp-controller="Order" asp-action="Index">
                                    <i class="bi bi-list"></i>Orders</a>
                            </li>
                                @if (Context.Session.GetString("Rid") == "3")
                                {
                                    <li>
                                      <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                                      <i class="bi bi-people"></i>&nbsp;Users</a>
                                    </li>
                                }
                        </ul>
                     </div>

                     <span style="padding: 5px;"></span>

                        <form asp-controller="Account" asp-action="Logout">
                            <button class="btn btn-outline-danger my-2 my-sm-0">
                              <i class="bi bi-box-arrow-in-right"></i> Log out
                            </button>
                        </form>
                    }
                    else
                    {
                        <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
                        <i class="bi bi-box-arrow-in-right"></i> Log in
                        </a>
                        <span style="padding: 5px;"></span>
                        <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
                        <i class="bi bi-person-plus"></i> Register
                        </a>
                    }
                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>